Refactor script .env access
A bunch of scripts were grepping around in the .env to make decisions.
They now use the config script in order to query the config json.

diff --git a/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-start b/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-start
--- a/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-start
+++ b/src/modules/adsb-feeder/filesystem/root/opt/adsb/docker-compose-start
@@ -1,7 +1,15 @@
 #!/bin/bash
 
-if [[ ! -f /opt/adsb/init-complete ]] && grep -e 'AF_IS_BASE_CONFIG_FINISHED=True' /etc/adsb/.env; then
-    echo "First time adsb-system-restart: stop bootstrap"
+if [ ! -f /opt/adsb/scripts/lib-common.bash ] ; then
+    echo "Missing /opt/adsb/scripts/lib-common.bash, unable to continue."
+    exit 1
+else
+    . /opt/adsb/scripts/lib-common.bash
+    rootcheck
+fi
+
+if [ "$(/opt/adsb/adsb-setup/config.py get base_config)" != True ] ; then
+    log $0 "First time adsb-system-restart: stop bootstrap"
     systemctl disable adsb-bootstrap
     systemctl stop adsb-bootstrap
     touch /opt/adsb/init-complete
